#ifndef __ERROR__CODE__H
#define __ERROR_CODE__H

#define _SUCCESS 0
#define _COMM_BUFFER_NO_DATA -999
#define _COMM_STATE_NOT_OPEN -100
#define _COMM_STATE_SET_FAIL -101
#define _COMM_PORT_NOT_OPEN -102
#define _COMM_PORT_NOT_EXIST -103
#define _COMM_SETUP_FAIL -104
#define _COMM_CLEAR_ERROR -105
#define _COMM_BUFFER_PORT_NOT_OPEN -106
#define _CONTROL_LOGIC_ITEM_EXCEED_MAX -130
#define _CONTROL_LOGIC_HEAP_ALLOC_FAIL -131
#define _CONTROL_LOGIC_ITEM_NOT_EXIST -132
#define _CONTROL_LOGIC_CONFIG_INDEX_NOT_EXIST -133
#define _CONTROL_LOGIC_NOT_SPECIFY_CONFIG_FILE -134
#define _CONTROL_LOGIC_FILE_CANNOT_OPEN -135
#define _CONTROL_LOGIC_PASSWORD_WRONG -150
#define _CONTROLLER_NO_DATA_RESPONSE -180
#define _LASER_NO_DATA_RESPONSE -1000
#define _LASER_NOT_DETECT_TEMPERATURE -1001
#define _LASER_WRONG_TEMPERATURE_DATA -1002

#define _CAMERA_NOT_FOUND -2000
#define _CAMERA_NOT_CONNECTED -2001
#define _FILE_NOT_OPEN -2100
#define _FILE_NOT_BITMAP -2101





#endif